### ISSUE TITLE
Option to automatically skip private folders

### ISSUE THREAD

**Issue by kingmustard** [deadlydog/PathLengthChecker#1]
If I'm searching inside a folder ("A") that has 5 sub-folders (1, 2, 3, 4, 5) and I don't have access to 3, the search within A fails and shows, "Access to the path 'xx' is denied."

This requires me to manually enter the 1, 2, 4 and 5 folder paths into the program ton continue.

Could there be an option in v1.1.2 to automatically skip private folders and continue searching?

Fantastic program, @deadlydog, by the way.

**Comment by deadlydog** [comment]
Thanks @kingmustard :)

Yeah, I agree that this is a pain. The problem is that right now I use `System.IO.Directory` to recursively enumerate all of the files and directories, and it does not provide any option to "ignore and continue" when these errors occur. I think I would need to change the library being used to enumerate over all of the files an directories to fix this issue. Hopefully I'll find time to look into this more. In the meantime I'm open to accepting pull requests ;)
