### ISSUE TITLE
Skip non-accessible folders

### ISSUE THREAD

**Issue by bsto** [deadlydog/PathLengthChecker#2]
When I run PathLengthChecker over the whole partiton D: of my 64bit Win 7 system and the prgm comes to the system folder "System Volume Information" it pops up an error

"Cannot access System Volume Information"

and aborts.

Next release of PathLengthChecker should automatically skip these kind of folder.

Ben

**Comment by deadlydog** [comment]
Yeah, I agree that this is a pain. The problem is that right now I use `System.IO.Directory` to recursively enumerate all of the files and directories, and it does not provide any option to "ignore and continue" when these errors occur. I think I would need to change the library being used to enumerate over all of the files an directories to fix this issue. Hopefully I'll find time to look into this more. In the meantime I'm open to accepting pull requests ;)

**Comment by teknowledgist** [comment]
I'm not versed in C-sharp, but it appears that the only solution to this problem is building your own recursive function.  There is a good article on exactly this problem and [the *directory-only* solution here](http://www.blackwasp.co.uk/FolderRecursion.aspx).  Folding in the files too should be do-able.

Good luck.

**Comment by A9G-Data-Droid** [comment]
I dug in to this and found that the `EnumerateDirectories` will support `EnumerationOptions.IgnoreInaccessible` Property starting in .NET 5, which is in preview at the time of this writing:

https://docs.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.ignoreinaccessible?view=netcore-3.1#System_IO_EnumerationOptions_IgnoreInaccessible
