### ISSUE TITLE
Show progress indicator/number of already processed files

### ISSUE THREAD

**Issue by bsto** [deadlydog/PathLengthChecker#3]
When I run PathLengthChecker over the whole partiton D: of my 64bit Win 7 system then the run lasts very long since there are many, many files.

To give the user a rough estimation about the already done work PathLengthCehcker should show
either a percentage value or number of already processed files or file name of currently investigated files (if processing in alphabetical sort order).

Can you implement it in the next release?

Ben

**Comment by deadlydog** [comment]
Yeah, that would be a nice feature. The current implementation uses the `System.IO.Directory` class for enumerating over all of the directories and files, and unfortunately it does not give any sort of progress indicator. However, I may need to look at using a different class anyways since that one does not give anyway to tell it to "ignore and continue" when it attempts to read a directory that the user does not have access to. I'll keep this in mind if/when I update the tool to use a different method for enumerating the files/directories. Thanks!
