### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by anonimuos** [deadlydog/PathLengthChecker#48]
The Monospaced font is kind of hard to read for me. Is there a way to change the font without reverting to earlier version?

**Comment by deadlydog** [comment]
No, I'll need to publish a new version. v1.8 is using `Courier New` for the paths grid. Below is a screenshot using `Lucida Console`; are you able to read it better? You can compare it with [this one](https://github.com/deadlydog/PathLengthChecker/blob/master/docs/Images/PathLengthChecker.png) that shows Courier New.

I need to take care about which font I specify, as I want to be sure it comes with native Windows to ensure that all users will have it installed.

![image](https://user-images.githubusercontent.com/1187140/97200202-87642880-1776-11eb-8b08-a079de4587bd.png)

**Comment by anonimuos** [comment]
No I like only normal looking fonts like Arial, Segoe UI, Tahoma or MS Sans Serif. These console fonts look weird but I guess it's ok with me if you like it as a developer.

**Comment by deadlydog** [comment]
Thanks for the feedback. Since this app's purpose is to find path lengths, I think it makes more sense to use a monospaced font, as it looked a bit odd having a 20 character path "appear" to be longer than a 30 character path, simply because it used a lot of "smaller" letters, like `l` and `i`. I'm going to stick with things as they are unless more people provide similar feedback. Thanks for your input though!
