### ISSUE TITLE
Request: count spaces as 3 characters

### ISSUE THREAD

**Issue by Muramas** [deadlydog/PathLengthChecker#58]
As our company is going to sharepoint. I want to make sure that the file lengths are below a certain number of characters. Each space is equal to 3 characters as its encoded to %20 on sharepoint.

Could there be a function that adds this calculation?

**Comment by deadlydog** [comment]
Thanks for the suggestion @Muramas. I've added a new "Url encode paths" option in v1.11.1, so it will convert spaces to %20, backslashes to %5C, etc. Give it a try and let me know what you think 🙂

**Comment by Muramas** [comment]
OMG this is amazing work and very quick at implementing.
Thank you so much!

**Comment by deadlydog** [comment]
Cool, I'm glad it works for you. I do accept donations 😉 haha.

Also, I found a bug when using both the Starting Directory Replacement and the new URL Encoding options together. It's fixed in v1.11.4.

I'm going to go ahead and close this one since I believe it's resolved. If you run into any issues though feel free to report it. Thanks!
